# Generated by Django 5.2.1 on 2025-05-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemprompt',
            options={'ordering': ['-updated_at'], 'verbose_name': '系统提示词', 'verbose_name_plural': '系统提示词'},
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='category',
            field=models.CharField(choices=[('general', '通用提示词'), ('mechanics', '力学'), ('electromagnetism', '电磁学'), ('thermodynamics', '热力学'), ('fluid', '流体力学'), ('quantum', '量子物理'), ('relativity', '相对论'), ('optics', '光学')], default='general', max_length=30, verbose_name='物理领域分类'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='name',
            field=models.CharField(max_length=100, verbose_name='提示词名称'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='prompt',
            field=models.TextField(verbose_name='提示词内容'),
        ),
    ]
